#!/usr/bin/env node
// Reads tools/figures/svg/*.svg + figures.json and emits
// site/components/figures/course-figures.tsx — the single file pushed to v0.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, "..", "..")
const svgDir = join(here, "svg")
const meta = JSON.parse(readFileSync(join(here, "figures.json"), "utf8"))

const files = readdirSync(svgDir).filter(f => /^fig-\d\d\.svg$/.test(f)).sort()
if (!files.length) { console.error("no figures in", svgDir); process.exit(1) }

const esc = s => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")

const entries = files.map(f => {
  const n = f.match(/^fig-(\d\d)\.svg$/)[1]
  const info = meta.figures.find(x => String(x.n).padStart(2, "0") === n)
  if (!info) throw new Error(`figures.json has no entry for ${f}`)
  let svg = readFileSync(join(svgDir, f), "utf8").trim()
  // strip any XML prolog / comments; keep just the <svg> element
  svg = svg.replace(/^<\?xml[^>]*\?>\s*/, "").replace(/<!--[\s\S]*?-->/g, "").trim()
  if (!svg.startsWith("<svg")) throw new Error(`${f} does not start with <svg`)
  const groups = (svg.match(/<g[\s>]/g) || []).length
  return { n, info, svg, groups }
})

const maxGroups = Math.max(...entries.map(e => e.groups), 1)
const delays = Array.from({ length: maxGroups }, (_, i) =>
  `.cfig[data-on="true"] > svg > g:nth-of-type(${i + 1}){transition-delay:${i * 70}ms}`).join("")

const out = `// GENERATED by tools/figures/build.mjs — do not edit by hand.
// Source of truth: tools/figures/svg/*.svg  (edit those, then \`node tools/figures/build.mjs\`)
"use client"

import { useEffect, useRef, useState } from "react"

const STYLE = \`
.cfig > svg { display:block; width:100%; height:auto; }
.cfig > svg > g { opacity:0; transform:translateY(8px);
  transition:opacity .55s cubic-bezier(.22,1,.36,1), transform .55s cubic-bezier(.22,1,.36,1); }
.cfig[data-on="true"] > svg > g { opacity:1; transform:none; }
${delays}
@media (prefers-reduced-motion: reduce){
  .cfig > svg > g { opacity:1; transform:none; transition:none; }
}\`

function Reveal({ svg, label }: { svg: string; label: string }) {
  const ref = useRef<HTMLDivElement>(null)
  const [on, setOn] = useState(false)
  useEffect(() => {
    const el = ref.current
    if (!el) return
    if (typeof IntersectionObserver === "undefined") { setOn(true); return }
    const io = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) { setOn(true); io.disconnect() } },
      { rootMargin: "0px 0px -12% 0px" },
    )
    io.observe(el)
    return () => io.disconnect()
  }, [])
  return (
    <>
      <style>{STYLE}</style>
      <div ref={ref} className="cfig" data-on={on} role="img" aria-label={label}
        dangerouslySetInnerHTML={{ __html: svg }} />
    </>
  )
}

${entries.map(e => `const SVG_${e.n} = \`${esc(e.svg)}\`
/** Figure ${e.info.n} — ${e.info.name} (${e.info.modules}) */
export function Fig${e.n}() { return <Reveal svg={SVG_${e.n}} label={${JSON.stringify(e.info.one_idea)}} /> }`).join("\n\n")}

export const figureCaptions: Record<string, string> = {
${entries.map(e => `  "${e.n}": ${JSON.stringify(e.info.caption)},`).join("\n")}
}
`

const dest = join(repo, "site", "components", "figures")
mkdirSync(dest, { recursive: true })
writeFileSync(join(dest, "course-figures.tsx"), out)
console.log(`wrote site/components/figures/course-figures.tsx`)
for (const e of entries) console.log(`  Fig${e.n}  ${e.groups} groups  ${e.svg.length}b  ${e.info.name}`)
