export const courseModules = [
  { title: "What is an LLM?", description: "Tokens, probabilities, and how a model turns your words into a reply.", project: "Your first call.", sections: ["What an LLM is", "Tokens: what the model reads", "A probability machine", "One token at a time", "Temperature: choosing from the list", "Where the model came from", "The context window", "Talking to it: prompts and conversations", "What it gets wrong", "The whole picture", "Project: your first call"] },
  { title: "Working with a model", description: "The API, the system prompt, examples, and getting answers in a shape your code can use.", project: "The note-to-actions tool.", sections: ["The API: a model you call from code", "The system prompt", "Show, don't tell: examples", "Structured output", "When the output is wrong", "Streaming and latency", "What it costs, and caching", "Project: the note-to-actions tool"] },
  { title: "Tools and the agent loop", description: "How a model that can only talk becomes one that can act.", project: "An agent that can look things up.", sections: ["A model can't do anything", "A tool is three things", "The round trip", "The loop", "The window is the loop variable", "When it picks the wrong tool", "MCP, briefly", "Project: an agent that can look things up"] },
  { title: "Memory and context", description: "What the model can see, what it forgets, and how to give it a memory.", project: "An agent that remembers.", sections: ["The window is all it has", "Short-term memory: the transcript", "Long-term memory: notes and files", "Retrieval", "Context rot", "Context engineering", "Project: an agent that remembers"] },
  { title: "Evals", description: "How you know it worked.", project: "A test suite for your agent.", sections: ["It seemed fine is not a test", "Golden cases", "Three ways to grade", "Traces are evidence", "Compounding errors", "Every time, automatically", "Project: a test suite for your agent"] },
  { title: "Failure modes and guardrails", description: "Hallucinated results, runaway loops, injection, cost blowups — and the checks that catch them.", project: "Guardrails.", sections: ["Make it break on purpose", "Made-up facts and made-up results", "Loops that never stop", "Prompt injection and the lethal trifecta", "Cost and latency blowups", "Guardrails", "Project: guardrails for your agent"] },
  { title: "Workflows and orchestration", description: "Chaining, routing, parallel, orchestrator–workers, and when not to use an agent at all.", project: "A two-agent system.", sections: ["Workflows first", "Chaining and routing", "Parallel: fan out, fan in", "Orchestrator and workers", "A critic in the loop", "Humans in the loop", "Project: a two-agent system"] },
  { title: "Capstone: The Desk", description: "A production multi-agent research system you deploy, trace, and show.", project: "The whole module.", sections: ["What you're building", "The orchestrator", "The specialists", "The harness", "Memory across runs", "Observability", "Evals and guardrails in CI", "Deploy and show it"] },
] as const
