"use client"

import Link from "next/link"
import { useState } from "react"
import { Eyebrow, Figure, LessonHeader, Prose } from "./reading-frame"
import { GoDeeper } from "@/components/figures/resource"
import { Fig01, Fig02, Fig08 } from "@/components/figures/course-figures"
import { Flow, KV, Note, Numbers, Stack, Steps, Table, Transcript } from "@/components/figures/kit"
import { LabPrompt } from "@/components/lab/lab-prompt"
import { YourRun } from "@/components/lab/your-run"
import { Bars } from "@/components/figures/charts"

export const sectionMeta = ["~6 min", "~7 min", "~8 min", "~6 min", "~7 min", "~8 min", "~6 min", "~8 min", "~7 min", "~5 min", "~25 min"] as const

type Lesson = { title: string; line: string; caption: string; figure: React.ReactNode; paragraphs: string[]; key: string; question?: string; options?: string[]; answers?: string[]; deeper?: string; url?: string }

const stackSteps = [
  { title: "Application", body: "Holds the conversation and sends the whole transcript every turn. § 8" },
  { title: "API", body: "Where the request leaves your code: text in, text out. § 1, § 11" },
  { title: "Tokenizer", body: "Chops the text into tokens on the way in, and back into text on the way out. § 2" },
  { title: "Model weights", body: "A huge file of numbers. Reads every token it can see and produces a list of next tokens, each with a probability. § 3, § 6, § 7" },
  { title: "GPU", body: "The hardware that runs the numbers. Skipped on purpose." },
  { title: "Sampling", body: "Picks one token from the list; temperature sets how adventurous the pick is. § 5" },
  { title: "Tokens back", body: "Append the pick, send the longer text back, repeat until the stop token. § 4" },
]

// § 5 — the same next-token list from Figure 3.1, sampled at two temperatures.
// Shape claim only (the section states no pick counts), so both titles say so.
const tempPicks = [
  { label: "sleep", value: 26 },
  { label: "cook", value: 21 },
  { label: "relax", value: 17 },
  { label: "read", value: 12 },
  { label: "thousands more", value: 24 },
]
const tempZero = tempPicks.map((d, i) =>
  ({ ...d, value: i === 0 ? 100 : 0, accent: i === 0 }))
const tempNoteLow = "Always the top bar, so the same reply every time. " +
  "Good for factual lookup, code."
const tempNoteHigh = "Spread across the list, so replies vary and drift. " +
  "Same list of odds both times; only the picking changed."
const tempFigure = (
  <Stack>
    <Bars
      title="Temperature 0 · share of picks · illustrative"
      unit="%"
      max={100}
      height={170}
      data={tempZero}
      note={tempNoteLow}
    />
    <Bars
      title="Temperature 1.5 · share of picks · illustrative"
      unit="%"
      max={100}
      height={170}
      data={tempPicks}
      note={tempNoteHigh}
    />
  </Stack>
)

const lessons: Lesson[] = [
{title:"What an LLM is",line:"A language model is a program that takes in text and produces the text most likely to come next.",caption:"FIGURE 1.1 — Text in, text out. Everything in this module is about what happens inside the box.",figure:<Stack><Flow items={[{label:"What's the capital of France?",sub:"text in"},{label:"model",accent:true,sub:"one small piece at a time"},{label:"Paris.",sub:"text out"}]} /><KV rows={[{k:"large",v:"the program is very big"},{k:"language",v:"it works on text"},{k:"model",v:"a program whose behavior was learned rather than written"}]} /></Stack>,paragraphs:["When you type into ChatGPT or Claude and get an answer back, you're using a large language model. The name sounds heavy. The idea is not.","A language model is a program. You give it text, and it gives you text back. That's the whole interface: words in, words out.","What makes it different is how it decides what to say. It learned from an enormous amount of written text what text tends to come next, and uses that to produce a reply one small piece at a time.","The word large means the program is very big. Language means it works on text. Model is the word for a program whose behavior was learned rather than written."],key:"A language model doesn't retrieve answers; it produces the text most likely to follow yours.",question:"Which is closest to what a language model does?",options:["It searches for the best answer in a database.","It follows rules written by engineers.","It produces the text most likely to come next after yours."],answers:["No — nothing is stored as an answer. It produces text.","The engineers wrote the program that runs it, not the behavior. The behavior was learned.","Yes. Hold onto that sentence; every section builds on it."],deeper:"Andrej Karpathy, Intro to Large Language Models",url:"https://www.youtube.com/watch?v=zjkBMFhNj_g"},
{title:"Tokens: what the model reads",line:"The model doesn't read words or letters; it reads pieces of text called tokens.",caption:"FIGURE 2.1 — The same sentence, the way the model sees it.",figure:<Table head={["text","what the model sees","tokens"]} accentCol={2} rows={[["The quick brown fox jumps over the lazy dog","The · quick · brown · fox · jumps · over · the · lazy · dog","9"],["unbelievably","un · believ · ably","3"]]} />,paragraphs:["Before the model can do anything with your text, the text is chopped into pieces. The pieces are called tokens.","A token is often a whole word, but not always. Common words are usually one token. Long or rare words get split into several. Punctuation is its own token.","This explains why a model can miscount the letters in strawberry — it never saw the letters, only the pieces. It's also why prices and limits are measured in tokens.","The tokenizer does the chopping before the model and after it. From here on, next piece means next token."],key:"Everything the model reads and writes is made of tokens, and that's the unit it's priced and limited in.",question:"Why might a model miscount the letters in a word?",options:["It's bad at arithmetic.","It reads tokens, not letters, so letters inside a token are invisible to it.","It wasn't trained on spelling."],answers:["That's a different problem. This one is about what it can see.","Yes.","It saw plenty of spelling — in pieces."],deeper:"tiktokenizer",url:"https://tiktokenizer.vercel.app/"},
{title:"A probability machine",line:"Given some text, the model produces a list of possible next tokens, each with a probability.",caption:"FIGURE 3.1 — Not an answer. A list of possible next tokens, with odds.",figure:<Fig08 />,paragraphs:["When the model reads your text, it doesn't decide on a next token. It produces a list — every token it knows, ranked by how likely it is to come next, with a probability beside each one.","For a sentence about rain, sleep might be at the top with about nine percent, then cook, then relax, and thousands of less likely tokens.","That list is the model's entire output. Everything you've read from a chatbot started as a list like this.","One tall bar means the model is sure. A few medium bars means it's torn. A long flat spread means the text could go almost anywhere."],key:"The model's output is a probability list over next tokens; choosing one from it is a separate step.",question:"What does the model produce when it reads your text?",options:["The single best next token.","A ranked list of possible next tokens, each with a probability.","The complete reply."],answers:["It produces the whole list. Picking one happens next.","Yes.","No — one token's worth of odds at a time."],deeper:"Google's Machine Learning Crash Course, Introduction to LLMs",url:"https://developers.google.com/machine-learning/crash-course/llm"},
{title:"One token at a time",line:"A reply is made by picking a token from the list, adding it to the text, and asking for the list again — thousands of times.",caption:"FIGURE 4.1 — Pick, append, repeat.",figure:<Fig01 />,paragraphs:["A list of odds isn't a reply. To get a reply, the program picks one token, adds it to the end of the text, and sends the longer text back for a fresh list.","Then it picks again. Each pick adds one token. The loop runs until a special stop token ends the reply.","This is why an answer appears a few characters at a time. Each piece was one trip around the loop.","There is no plan for how a sentence will end when it starts. There is a good next guess, followed by another good next guess."],key:"Generation is a loop: one token per pass, each pass seeing everything so far.",question:"Why does a chatbot's reply appear in pieces?",options:["For effect — the whole answer exists first.","Because each token is chosen and sent one at a time.","Because the internet is slow."],answers:["It doesn't. Each piece is chosen after the previous one.","Yes.","Not the cause — the pieces really are made one at a time."],deeper:"3Blue1Brown, But what is a GPT?",url:"https://www.3blue1brown.com/lessons/gpt"},
]

const later: Record<number, Lesson> = {
5:{title:"Temperature: choosing from the list",line:"Temperature controls how the next token is picked from the list: low means always the top bar, high means spread the picks out.",caption:"FIGURE 5.1 — The same list, picked from differently.",figure:tempFigure,paragraphs:["Ask a chatbot the same question twice and you may get two different answers. The list of odds was the same both times. What changed was the picking.","There's a setting that decides how the picking works. It's called temperature.","Turn it all the way down, and the program always takes the top bar. Turn it up, and the picks spread out across the list.","Low temperature is useful for factual lookup or code. Higher temperature is useful for brainstorming or a poem."],key:"Temperature doesn't change what the model knows; it changes how adventurous the pick is.",question:"You want the same answer every time you ask. Which way do you turn temperature?",options:["Down to zero.","Up high.","It doesn't matter."],answers:["Yes — always the top bar.","That spreads the picks and makes replies vary more.","It's the main thing that does matter here."],deeper:"Stephen Wolfram, What Is ChatGPT Doing",url:"https://writings.stephenwolfram.com/2023/02/what-is-chatgpt-doing-and-why-does-it-work/"},
6:{title:"Where the model came from",line:"A model is a huge file of numbers plus a small program; the numbers were found by training on a large slice of the internet.",caption:"FIGURE 6.1 — Two files, and where the big one came from.",figure:<Stack><Numbers items={[{value:"10 TB",label:"text read in training"},{value:"140 GB",label:"parameters — nothing but numbers",accent:true},{value:"~500",label:"lines of code that run them"}]} /><Flow items={["guess the next token","check the guess","nudge the numbers"]} loop /></Stack>,paragraphs:["We've been saying the model as if it's a place. It's a thing you could carry.","A model is two files. One is enormous and contains nothing but numbers. The other is small, a few hundred lines of code, and runs your tokens through those numbers.","Nobody typed the numbers in. They were found by training: guess the next token, check the guess, and nudge the numbers toward a better guess, over and over.","The result is a compressed, lossy copy of what it read. Nothing inside it is stored as a fact. Patterns are blurred into the numbers."],key:"Training turns a library into a list of numbers, and what's known is blurred in, not stored.",question:"Where is the model's knowledge kept?",options:["In a database of facts.","Blurred into billions of numbers as patterns.","In rules inside the small program."],answers:["There's no database. Nothing in the file looks like a fact.","Yes.","The small program only knows how to use the numbers."],deeper:"Karpathy, Intro to LLMs",url:"https://www.youtube.com/watch?v=zjkBMFhNj_g"},
7:{title:"The context window",line:"The model can only see a fixed number of tokens at once; that span is the context window.",caption:"FIGURE 7.1 — Everything the model can see right now.",figure:<Fig02 />,paragraphs:["Every pass through the loop, the model sees all the text so far. But not infinitely far. There's a limit on how many tokens it can take in at once, and that limit is the context window.","Think of it as the model's field of view. Everything inside it is visible on every pass. Anything outside it might as well not exist.","This is why a long conversation can drift: the early part slid out of the window.","Bigger windows are not free, and seeing text is not the same as using it well."],key:"The model sees a window of tokens, not a history; what's outside the window is gone.",question:"A conversation has grown longer than the window. What does the model see?",options:["All of it, more blurrily.","Only the most recent part that fits.","A summary it keeps for itself."],answers:["It doesn't blur. Out is out.","Yes.","Not on its own — that's something you build."],deeper:"Learn AI Visually, Context engineering",url:"https://learnaivisually.com/tracks/ai-agents/context-engineering"},
8:{title:"Talking to it: prompts and conversations",line:"Your text is the prompt, the model's text is the completion, and a conversation is just the whole transcript sent again each turn.",caption:"FIGURE 8.1 — A conversation is a transcript, re-sent in full.",figure:<Stack><Transcript title="What gets sent on the second turn" turns={[{role:"system",text:"Standing instructions from the app."},{role:"user",text:"Your first message — the prompt."},{role:"assistant",text:"The model's reply — the completion."},{role:"user",text:"Your new message. The three above travel with it."}]} /><Note label="Every turn">The model has no memory. The whole transcript so far is sent again and read fresh; when it outgrows the window, it forgets.</Note></Stack>,paragraphs:["The text you send is called the prompt. The text the model produces is called the completion.","The model has no memory. Each time you send a message, the whole conversation so far is sent along with it. The model reads all of it fresh.","That's why it remembers your name: your name is in the transcript it was just handed. When the transcript outgrows the window, it forgets.","Messages have roles: system, user, and assistant. The system message contains standing instructions from the app."],key:"The model never remembers; the app re-sends everything, and roles tell it who said what.",question:"You told a chatbot your name three messages ago and it still knows it. Why?",options:["It saved your name.","The whole conversation is re-sent every turn.","It recognizes you."],answers:["It saved nothing. It was handed the transcript.","Yes.","It recognizes text — and your name was in the text."],deeper:"Karpathy, Intro to LLMs",url:"https://www.youtube.com/watch?v=zjkBMFhNj_g"},
9:{title:"What it gets wrong",line:"The model produces plausible text, and plausible is not the same as true.",caption:"FIGURE 9.1 — Confident, fluent, and made up.",figure:<Stack><Transcript turns={[{role:"user",text:"What's the weather in Austin right now?"},{role:"assistant",text:"It's 84°F and partly cloudy, with a light breeze from the south.",note:"no tools · no internet · no way to check"}]} /><Note label="Hallucination">It isn't lying, and it isn't broken. It's producing likely next tokens in a situation where the truth isn't available to it.</Note></Stack>,paragraphs:["Ask a model with no internet access what the weather is right now in Austin. It will tell you. It has no way to know any of it.","It isn't lying, and it isn't broken. It's producing likely next tokens in a situation where the truth isn't available to it.","This is hallucination: a probability machine whose knowledge is a blur has no way to tell likely from so.","The fix isn't a better prompt. Give the model tools to look things up, and checks on what it produces. That is the rest of this book."],key:"Hallucination is what a plausible-text machine does when the truth isn't in view.",question:"What should you do with a fluent answer to a question the model cannot check?",options:["Trust the confidence.","Verify it with a source or tool.","Ask it to sound more certain."],answers:["Fluency is not evidence.","Yes.","Confidence cannot create missing information."],deeper:"Andrew Ng, Agentic Design Patterns",url:"https://www.deeplearning.ai/the-batch/agentic-design-patterns-part-1"},
10:{title:"The whole picture",line:"You can now read every step between typing a question and getting a reply.",caption:"FIGURE 10.1 — A request's path, top to bottom, and the tokens' path back.",figure:<Steps accent={3} items={stackSteps} />,paragraphs:["Ten sections ago this was a box labeled model. Now every layer has a name and a section behind it.","We skipped hardware, memory tricks, and the math inside the box on purpose. They're real and interesting, but not where you get stuck using or building with a model.","Everything in the next six modules is built on top of this text-in, text-out probability machine."],key:"A model is a text-in, text-out probability machine, and everything in the next six modules is built on top of it.",deeper:"Transformer Explainer",url:"https://poloclub.github.io/transformer-explainer/"},
11:{title:"Project: your first call",line:"One line to your agent sets up the lab; then you make one real call to a model and read your own numbers.",caption:"FIGURE 11.1 — The same chart. Your prompt, your numbers.",figure:<Stack><LabPrompt module={1} /><YourRun module={1} /></Stack>,paragraphs:["Everything so far happened in your browser. This section gives you your own copy of it.","Paste the line above into whichever coding agent you already use. It clones the course, sets it up, asks you for an API key, and then becomes your tutor — one that has been told not to write your code for you.","Your first job is one real call to a model. Run it three times, at temperature 0, 0.7, and 1.5, and read the three replies. Each run writes a trace, and the panel above fills in with your own numbers."],key:"You've now done, in your own code, everything this module described."}
}

function Check({lesson}:{lesson:Lesson}) { const [selected,setSelected]=useState<number|null>(null); if(!lesson.options) return null; return <section className="mt-12 border border-border p-5"><Eyebrow>Check</Eyebrow><p className="mt-3 text-sm leading-6">{lesson.question}</p><div className="mt-4 grid gap-2">{lesson.options.map((o,i)=><button key={o} onClick={()=>setSelected(i)} className={`border px-3 py-3 text-left text-sm ${selected===i?"border-foreground":"border-border"}`}><span className="mr-2 font-mono text-[10px]">{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{selected!==null&&<p className="mt-4 border-t border-border pt-4 text-sm leading-6 text-muted-foreground">{lesson.answers?.[selected]}</p>}</section> }

export function LessonOne({section=1}:{section?:number}) { const lesson=lessons[section-1]??later[section]; const item=lesson??lessons[0]; return <article><LessonHeader eyebrow={`Module 01 · Section ${section} of 11`} meta={sectionMeta[section-1]??"~7 min"}>{item.title}</LessonHeader><div className="mt-10 border border-border px-4 py-3"><Eyebrow>In one line</Eyebrow><p className="mt-2 text-lg leading-7">{item.line}</p></div><Figure caption={item.caption}>{item.figure}</Figure><Prose>{item.paragraphs.map(p=><p key={p}>{p}</p>)}</Prose><aside className="mt-10 border border-border p-5"><Eyebrow>Key idea</Eyebrow><p className="mt-2 text-sm leading-6">{item.key}</p></aside><Check lesson={item}/>{item.deeper&&<GoDeeper title={item.deeper} url={item.url} />}<div className="mt-12 flex items-center justify-between border-t border-border pt-6 font-mono text-[10px]"><Link href={section>1?`/m/1/s/${section-1}`:"/m/1"}>← Previous</Link>{section<11?<Link className="text-foreground" href={`/m/1/s/${section+1}`}>Next →</Link>:<Link className="text-foreground" href="/m/2">Next: Module 02 — Working with a model →</Link>}</div></article> }
export function LessonShell({lesson}:{lesson:number}){return <LessonOne section={lesson}/>}
export { sectionMeta as lessonMeta }
export const moduleSections = lessons.map(x=>x.title).concat(Object.values(later).map(x=>x.title).slice(4))
export function StackFigure(){return <Figure caption="FIGURE 10.1 — A request's path, top to bottom, and the tokens' path back."><Steps accent={3} items={stackSteps} /></Figure>}
