// GENERATED by tools/figures/build.mjs — do not edit by hand.
// Source of truth: tools/figures/svg/*.svg  (edit those, then `node tools/figures/build.mjs`)
"use client"

import { useEffect, useRef, useState } from "react"

const STYLE = `
.cfig > svg { display:block; width:100%; height:auto; }
.cfig > svg > g { opacity:0; transform:translateY(8px);
  transition:opacity .55s cubic-bezier(.22,1,.36,1), transform .55s cubic-bezier(.22,1,.36,1); }
.cfig[data-on="true"] > svg > g { opacity:1; transform:none; }
.cfig[data-on="true"] > svg > g:nth-of-type(1){transition-delay:0ms}.cfig[data-on="true"] > svg > g:nth-of-type(2){transition-delay:70ms}.cfig[data-on="true"] > svg > g:nth-of-type(3){transition-delay:140ms}.cfig[data-on="true"] > svg > g:nth-of-type(4){transition-delay:210ms}.cfig[data-on="true"] > svg > g:nth-of-type(5){transition-delay:280ms}.cfig[data-on="true"] > svg > g:nth-of-type(6){transition-delay:350ms}.cfig[data-on="true"] > svg > g:nth-of-type(7){transition-delay:420ms}
@media (prefers-reduced-motion: reduce){
  .cfig > svg > g { opacity:1; transform:none; transition:none; }
}`

function Reveal({ svg, label }: { svg: string; label: string }) {
  const ref = useRef<HTMLDivElement>(null)
  const [on, setOn] = useState(false)
  useEffect(() => {
    const el = ref.current
    if (!el) return
    if (typeof IntersectionObserver === "undefined") { setOn(true); return }
    const io = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) { setOn(true); io.disconnect() } },
      { rootMargin: "0px 0px -12% 0px" },
    )
    io.observe(el)
    return () => io.disconnect()
  }, [])
  return (
    <>
      <style>{STYLE}</style>
      <div ref={ref} className="cfig" data-on={on} role="img" aria-label={label}
        dangerouslySetInnerHTML={{ __html: svg }} />
    </>
  )
}

const SVG_01 = `<svg viewBox="0 0 960 340" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="ink1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="mut1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="input">
    <rect x="128" y="117" width="52" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <rect x="188" y="117" width="40" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <rect x="236" y="117" width="64" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <rect x="308" y="117" width="34" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
  </g>

  <g id="slot">
    <rect x="350" y="117" width="72" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5" stroke-dasharray="4 5" opacity=".55"/>
  </g>

  <g id="feed">
    <path d="M438 130 H470" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#mut1)"/>
  </g>

  <g id="model">
    <rect x="490" y="70" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="590" y="136" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="emit">
    <path d="M690 130 H738" stroke="currentColor" stroke-width="2.5" marker-end="url(#ink1)"/>
  </g>

  <g id="token">
    <text x="788" y="100" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">next token</text>
    <rect x="752" y="116" width="72" height="28" rx="14" fill="currentColor"/>
  </g>

  <g id="append">
    <path d="M788 144 V258 H386 V152" stroke="currentColor" stroke-width="2.5" marker-end="url(#ink1)"/>
    <text x="587" y="244" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">append</text>
  </g>
</svg>`
/** Figure 1 — Text in, text out (M1 s1–s4) */
export function Fig01() { return <Reveal svg={SVG_01} label={"The model turns text into one more token, appends it, and does it again."} /> }

export const figureCaptions: Record<string, string> = {
  "01": "FIGURE 1 — Pick, append, repeat. That loop is all generation is.",
}
