// GENERATED by tools/figures/build.mjs — do not edit by hand.
// Source of truth: tools/figures/svg/*.svg  (edit those, then `node tools/figures/build.mjs`)
"use client"

import { useEffect, useRef, useState } from "react"

const STYLE = `
.cfig { --fig-bg: color-mix(in oklab, var(--secondary) 30%, var(--background)); }
.cfig > svg { display:block; width:100%; height:auto; }
.cfig > svg > g { opacity:0; transform:translateY(8px);
  transition:opacity .55s cubic-bezier(.22,1,.36,1), transform .55s cubic-bezier(.22,1,.36,1); }
.cfig[data-on="true"] > svg > g { opacity:1; transform:none; }
.cfig[data-on="true"] > svg > g:nth-of-type(1){transition-delay:0ms}.cfig[data-on="true"] > svg > g:nth-of-type(2){transition-delay:70ms}.cfig[data-on="true"] > svg > g:nth-of-type(3){transition-delay:140ms}.cfig[data-on="true"] > svg > g:nth-of-type(4){transition-delay:210ms}.cfig[data-on="true"] > svg > g:nth-of-type(5){transition-delay:280ms}.cfig[data-on="true"] > svg > g:nth-of-type(6){transition-delay:350ms}.cfig[data-on="true"] > svg > g:nth-of-type(7){transition-delay:420ms}.cfig[data-on="true"] > svg > g:nth-of-type(8){transition-delay:490ms}.cfig[data-on="true"] > svg > g:nth-of-type(9){transition-delay:560ms}.cfig[data-on="true"] > svg > g:nth-of-type(10){transition-delay:630ms}
@media (prefers-reduced-motion: reduce){
  .cfig > svg > g { opacity:1; transform:none; transition:none; }
}
/* On a phone a 960-unit drawing lands at ~343px, which drops 13/15u labels below
   readability. font-size on SVG text is in USER UNITS, so bumping it here scales
   the type up relative to the drawing instead of shrinking with it. */
@media (max-width: 640px){
  .cfig > svg text[font-size="13"] { font-size: 19px; }
  .cfig > svg text[font-size="14"] { font-size: 20px; }
  .cfig > svg text[font-size="15"] { font-size: 21px; }
}`

function Reveal({ svg, label }: { svg: string; label: string }) {
  const ref = useRef<HTMLDivElement>(null)
  const [on, setOn] = useState(false)
  useEffect(() => {
    const el = ref.current
    if (!el) return
    if (typeof IntersectionObserver === "undefined") { setOn(true); return }
    const io = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) { setOn(true); io.disconnect() } },
      { rootMargin: "0px 0px -12% 0px" },
    )
    io.observe(el)
    return () => io.disconnect()
  }, [])
  return (
    <>
      <style>{STYLE}</style>
      <div ref={ref} className="cfig" data-on={on} role="img" aria-label={label}
        dangerouslySetInnerHTML={{ __html: svg }} />
    </>
  )
}

const SVG_01 = `<svg viewBox="0 0 960 340" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f01-ink1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f01-acc1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f01-mut1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f01-input">
    <rect x="128" y="117" width="52" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <rect x="188" y="117" width="40" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <rect x="236" y="117" width="64" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <rect x="308" y="117" width="34" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5"/>
  </g>

  <g id="f01-slot">
    <rect x="350" y="117" width="72" height="26" rx="13" stroke="var(--muted-foreground)" stroke-width="1.5" stroke-dasharray="4 5" opacity=".55"/>
  </g>

  <g id="f01-feed">
    <path d="M438 130 H470" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f01-mut1)"/>
  </g>

  <g id="f01-model">
    <rect x="490" y="70" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="590" y="136" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f01-emit">
    <path d="M690 130 H738" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f01-acc1)"/>
  </g>

  <g id="f01-token">
    <text x="788" y="100" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">next token</text>
    <rect x="752" y="116" width="72" height="28" rx="14" fill="var(--figure-accent)"/>
  </g>

  <g id="f01-append">
    <path d="M788 144 V258 H386 V152" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f01-acc1)"/>
    <text x="587" y="244" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">append</text>
  </g>
</svg>`
/** Figure 1 — Text in, text out (M1 s1–s4) */
export function Fig01() { return <Reveal svg={SVG_01} label={"The model turns text into one more token, appends it, and does it again."} /> }

const SVG_02 = `<svg viewBox="0 0 960 400" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f02-ink2" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f02-acc2" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f02-mut2" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f02-window">
    <text x="221" y="104" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">window</text>
    <rect x="136" y="122" width="170" height="184" rx="10" stroke="currentColor" stroke-width="2"/>
  </g>

  <g id="f02-contents">
    <rect x="156" y="146" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="156" y="172" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".35"/>
    <rect x="156" y="198" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".35"/>
    <rect x="156" y="224" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".35"/>
    <rect x="156" y="250" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
  </g>

  <g id="f02-all-of-it">
    <path d="M326 138 H352 V276 H326 V266 H342 V148 H326 Z" fill="var(--figure-accent)"/>
    <path d="M352 206 H510" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f02-acc2)"/>
    <text x="431" y="188" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">every call</text>
  </g>

  <g id="f02-model">
    <rect x="510" y="146" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="610" y="212" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f02-reply">
    <path d="M710 206 H766" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f02-mut2)"/>
    <rect x="780" y="191" width="88" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="780" y="203" width="62" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="780" y="215" width="74" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <text x="824" y="242" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">reply</text>
  </g>
</svg>`
/** Figure 2 — What the model sees (M1 s7–s8) */
export function Fig02() { return <Reveal svg={SVG_02} label={"The model keeps nothing between calls; the whole window is re-sent every time."} /> }

const SVG_03 = `<svg viewBox="0 0 960 420" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f03-ink3" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f03-acc3" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f03-mut3" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f03-boundary">
    <rect x="112" y="92" width="336" height="248" rx="14" stroke="var(--muted-foreground)" opacity=".55" stroke-width="1.5" stroke-dasharray="5 5"/>
    <text x="134" y="120" fill="var(--muted-foreground)" font-size="13" text-anchor="start">your code</text>
  </g>

  <g id="f03-tool">
    <rect x="248" y="226" width="64" height="64" rx="8" fill="var(--figure-accent)"/>
    <polyline points="289,234 273,258 286,258 271,282" fill="none" stroke="var(--fig-bg)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>
    <text x="280" y="314" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">tool</text>
  </g>

  <g id="f03-model">
    <rect x="648" y="92" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="748" y="158" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f03-toolcall">
    <path d="M648 152 H280 V214" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f03-acc3)"/>
    <text x="548" y="139" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">tool call</text>
  </g>

  <g id="f03-result">
    <path d="M312 258 H748 V212" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f03-mut3)"/>
    <text x="548" y="282" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">result</text>
  </g>
</svg>`
/** Figure 3 — Model, your code, tools (M3 s1–s3) */
export function Fig03() { return <Reveal svg={SVG_03} label={"The model never runs a tool. It asks, and your code runs it."} /> }

const SVG_04 = `<svg viewBox="0 0 960 460" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f04-ink1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f04-acc1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f04-mut1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f04-ring">
    <path d="M514.8 138.2 A122 122 0 0 1 548.1 195.5" stroke="var(--muted-foreground)" stroke-width="2" marker-end="url(#f04-mut1)"/>
    <path d="M548.1 256.5 A122 122 0 0 1 475.7 339.1" stroke="var(--muted-foreground)" stroke-width="2"/>
    <path d="M384.3 339.1 A122 122 0 0 1 311 253" stroke="var(--muted-foreground)" stroke-width="2"/>
    <path d="M311 199 A122 122 0 0 1 345.2 138.2" stroke="var(--muted-foreground)" stroke-width="2"/>
  </g>

  <g id="f04-model">
    <rect x="355" y="60" width="150" height="88" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="430" y="110" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f04-entry">
    <path d="M104 104 H355" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f04-mut1)"/>
    <text x="230" y="90" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">message</text>
  </g>

  <g id="f04-check">
    <path d="M552 204 L574 226 L552 248 L530 226 Z" stroke="currentColor" stroke-width="2"/>
    <text x="600" y="268" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">tool call?</text>
  </g>

  <g id="f04-tool">
    <rect x="398" y="316" width="64" height="64" rx="8" stroke="currentColor" stroke-width="2"/>
    <path d="M433 331 L421 350 H429 L427 365 L439 346 H431 Z" stroke="var(--muted-foreground)" stroke-width="1.5" stroke-linejoin="round"/>
    <text x="430" y="400" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">tool</text>
  </g>

  <g id="f04-result">
    <rect x="272" y="211" width="74" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="282" y="223" width="54" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="277" y="235" width="64" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <text x="258" y="231" fill="var(--muted-foreground)" font-size="13" text-anchor="end">result</text>
  </g>

  <g id="f04-exit">
    <path d="M574 226 H754" stroke="var(--figure-accent)" stroke-width="3" marker-end="url(#f04-acc1)"/>
    <rect x="770" y="211" width="84" height="6" rx="3" fill="var(--figure-accent)"/>
    <rect x="770" y="223" width="60" height="6" rx="3" fill="var(--figure-accent)"/>
    <rect x="770" y="235" width="72" height="6" rx="3" fill="var(--figure-accent)"/>
    <text x="809" y="196" fill="currentColor" font-size="13" text-anchor="middle">reply</text>
  </g>
</svg>`
/** Figure 4 — The agent loop (M3 s4–s6) */
export function Fig04() { return <Reveal svg={SVG_04} label={"An agent is that round trip repeated until the model stops asking."} /> }

const SVG_05 = `<svg viewBox="0 0 960 480" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f05-ink1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f05-acc1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f05-mut1" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f05-window">
    <rect x="268" y="56" width="170" height="220" rx="10" stroke="currentColor" stroke-width="2"/>
    <rect x="288" y="106" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="288" y="132" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="288" y="158" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
  </g>

  <g id="f05-placed">
    <rect x="288" y="184" width="130" height="16" rx="3" fill="var(--figure-accent)"/>
    <rect x="288" y="210" width="130" height="16" rx="3" fill="var(--figure-accent)"/>
  </g>

  <g id="f05-feed">
    <path d="M438 166 H548" stroke="currentColor" stroke-width="2" marker-end="url(#f05-ink1)"/>
  </g>

  <g id="f05-model">
    <rect x="548" y="106" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="648" y="172" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f05-memory">
    <rect x="295" y="350" width="116" height="55" fill="var(--fig-bg)"/>
    <path d="M295 350 V405" stroke="currentColor" stroke-width="2"/>
    <path d="M411 350 V405" stroke="currentColor" stroke-width="2"/>
    <path d="M295 405 A58 15 0 0 0 411 405" stroke="currentColor" stroke-width="2"/>
    <ellipse cx="353" cy="350" rx="58" ry="15" fill="var(--fig-bg)" stroke="currentColor" stroke-width="2"/>
    <text x="271" y="383" fill="currentColor" font-size="15" text-anchor="end">memory</text>
  </g>

  <g id="f05-read">
    <path d="M353 335 V276" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f05-acc1)"/>
    <text x="334" y="312" fill="var(--muted-foreground)" font-size="13" text-anchor="end">retrieved</text>
  </g>

  <g id="f05-write">
    <path d="M648 226 V378 H411" stroke="var(--muted-foreground)" stroke-width="1.5" stroke-dasharray="5 5" marker-end="url(#f05-mut1)"/>
    <text x="529" y="364" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">write</text>
  </g>
</svg>`
/** Figure 5 — Where memory lives (M4 s3) */
export function Fig05() { return <Reveal svg={SVG_05} label={"Memory is a place outside the window that you read in before the call and write back after."} /> }

const SVG_06 = `<svg viewBox="0 0 960 480" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f06-ink6" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f06-mut6" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f06-loop">
    <circle cx="480" cy="153" r="90" stroke="var(--muted-foreground)" stroke-width="2"/>
    <path d="M464.37 64.37 A90 90 0 0 1 495.63 64.37" stroke="var(--muted-foreground)" stroke-width="2" marker-end="url(#f06-mut6)"/>
  </g>

  <g id="f06-model">
    <rect x="422" y="123" width="116" height="60" rx="14" stroke="currentColor" stroke-width="2" fill="var(--fig-bg)"/>
    <text x="480" y="158" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f06-entry">
    <path d="M120 153 H388" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f06-mut6)"/>
  </g>

  <g id="f06-exit">
    <path d="M570 153 H840" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f06-mut6)"/>
  </g>

  <g id="f06-tool-wire">
    <path d="M480 243 V341" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f06-mut6)"/>
  </g>

  <g id="f06-tool">
    <rect x="452" y="343" width="56" height="56" rx="8" stroke="currentColor" stroke-width="2" fill="var(--fig-bg)"/>
    <path d="M483 354 L471 373 H479 L477 388 L489 369 H481 Z" stroke="var(--muted-foreground)" stroke-width="1.5" stroke-linejoin="round"/>
    <text x="480" y="422" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">tool</text>
  </g>

  <g id="f06-gate-in">
    <path d="M255 131 L277 153 L255 175 L233 153 Z" fill="var(--figure-accent)"/>
    <text x="255" y="200" fill="currentColor" font-size="13" text-anchor="middle">check</text>
  </g>

  <g id="f06-gate-out">
    <path d="M705 131 L727 153 L705 175 L683 153 Z" fill="var(--figure-accent)"/>
    <text x="705" y="200" fill="currentColor" font-size="13" text-anchor="middle">check</text>
  </g>

  <g id="f06-gate-tool">
    <path d="M480 271 L502 293 L480 315 L458 293 Z" fill="var(--figure-accent)"/>
    <text x="524" y="298" fill="currentColor" font-size="13" text-anchor="start">check</text>
  </g>
</svg>`
/** Figure 6 — Gates around the loop (M6 s6 (M5 s4)) */
export function Fig06() { return <Reveal svg={SVG_06} label={"Guardrails are checks your code owns on the wires in, out, and to the tools."} /> }

const SVG_07 = `<svg viewBox="0 0 960 480" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f07-ink7" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f07-mut7" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f07-input">
    <rect x="64" y="160" width="70" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="64" y="172" width="50" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="64" y="184" width="60" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <path d="M146 172 H185" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
  </g>

  <g id="f07-plan">
    <circle cx="215" cy="172" r="30" fill="var(--fig-bg)" stroke="currentColor" stroke-width="2"/>
    <rect x="200" y="164" width="30" height="16" rx="4" stroke="currentColor" stroke-width="1.5"/>
    <text x="215" y="130" fill="var(--muted-foreground)" font-size="15" text-anchor="middle">plan</text>
  </g>

  <g id="f07-fan-out">
    <path d="M242.3 159.6 L372.7 100.4" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
    <path d="M245 172 H370" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
    <path d="M242.3 184.4 L372.7 243.6" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
  </g>

  <g id="f07-research">
    <circle cx="400" cy="88" r="30" fill="var(--figure-accent)"/>
    <rect x="385" y="80" width="30" height="16" rx="4" fill="none" stroke="var(--fig-bg)" stroke-width="1.5"/>
    <circle cx="400" cy="172" r="30" fill="var(--figure-accent)"/>
    <rect x="385" y="164" width="30" height="16" rx="4" fill="none" stroke="var(--fig-bg)" stroke-width="1.5"/>
    <circle cx="400" cy="256" r="30" fill="var(--figure-accent)"/>
    <rect x="385" y="248" width="30" height="16" rx="4" fill="none" stroke="var(--fig-bg)" stroke-width="1.5"/>
    <text x="400" y="314" fill="currentColor" font-size="15" text-anchor="middle">research</text>
  </g>

  <g id="f07-fan-in">
    <path d="M427.3 100.4 L557.7 159.6" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
    <path d="M430 172 H555" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
    <path d="M427.3 243.6 L557.7 184.4" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
  </g>

  <g id="f07-check">
    <circle cx="585" cy="172" r="30" fill="var(--fig-bg)" stroke="currentColor" stroke-width="2"/>
    <rect x="570" y="164" width="30" height="16" rx="4" stroke="currentColor" stroke-width="1.5"/>
    <text x="585" y="130" fill="var(--muted-foreground)" font-size="15" text-anchor="middle">check</text>
    <path d="M615 172 H700" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
  </g>

  <g id="f07-write">
    <circle cx="730" cy="172" r="30" fill="var(--fig-bg)" stroke="currentColor" stroke-width="2"/>
    <rect x="715" y="164" width="30" height="16" rx="4" stroke="currentColor" stroke-width="1.5"/>
    <text x="730" y="130" fill="var(--muted-foreground)" font-size="15" text-anchor="middle">write</text>
    <path d="M760 172 H798" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
  </g>

  <g id="f07-output">
    <rect x="808" y="160" width="80" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="808" y="172" width="56" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="808" y="184" width="68" height="6" rx="3" fill="var(--muted-foreground)" opacity=".5"/>
    <text x="844" y="130" fill="var(--muted-foreground)" font-size="15" text-anchor="middle">brief</text>
  </g>

  <g id="f07-memory">
    <path d="M171 320 V358 A44 12 0 0 0 259 358 V320" fill="var(--fig-bg)" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <ellipse cx="215" cy="320" rx="44" ry="12" fill="var(--fig-bg)" stroke="var(--muted-foreground)" stroke-width="1.5"/>
    <text x="215" y="390" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">memory</text>
    <path d="M215 308 V202" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f07-mut7)"/>
  </g>

  <g id="f07-trace">
    <path d="M370 408 H888" stroke="var(--border)" stroke-width="1.5"/>
    <path d="M400 408 V300" stroke="var(--border)" stroke-width="1.5" stroke-dasharray="3 5"/>
    <path d="M585 408 V216" stroke="var(--border)" stroke-width="1.5" stroke-dasharray="3 5"/>
    <path d="M730 408 V216" stroke="var(--border)" stroke-width="1.5" stroke-dasharray="3 5"/>
    <text x="352" y="412" fill="var(--muted-foreground)" font-size="13" text-anchor="end">trace</text>
  </g>
</svg>`
/** Figure 7 — Many loops — the Desk (M7 s3–s4, M8 s1–s3) */
export function Fig07() { return <Reveal svg={SVG_07} label={"A system is several copies of the same loop, each with its own window, wired in a line."} /> }

const SVG_08 = `<svg viewBox="0 0 960 360" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f08-ink8" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f08-model">
    <rect x="64" y="90" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="164" y="156" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f08-emit">
    <path d="M264 150 H330" stroke="currentColor" stroke-width="2" marker-end="url(#f08-ink8)"/>
  </g>

  <g id="f08-bars">
    <rect x="416" y="90"  width="400" height="16" rx="3" fill="var(--figure-accent)"/>
    <rect x="416" y="118" width="210" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="416" y="146" width="138" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="416" y="174" width="84"  height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
  </g>

  <g id="f08-labels">
    <text x="400" y="103" fill="currentColor" font-size="13" text-anchor="end">sleep</text>
    <text x="400" y="131" fill="var(--muted-foreground)" font-size="13" text-anchor="end">cook</text>
    <text x="400" y="159" fill="var(--muted-foreground)" font-size="13" text-anchor="end">relax</text>
    <text x="400" y="187" fill="var(--muted-foreground)" font-size="13" text-anchor="end">read</text>
    <text x="828" y="103" fill="var(--muted-foreground)" font-size="13">9%</text>
  </g>

  <g id="f08-tail">
    <rect x="416" y="204" width="62" height="3" rx="1.5" fill="var(--muted-foreground)" opacity=".26"/>
    <rect x="416" y="215" width="44" height="3" rx="1.5" fill="var(--muted-foreground)" opacity=".23"/>
    <rect x="416" y="226" width="31" height="3" rx="1.5" fill="var(--muted-foreground)" opacity=".2"/>
    <rect x="416" y="237" width="21" height="3" rx="1.5" fill="var(--muted-foreground)" opacity=".17"/>
    <rect x="416" y="248" width="14" height="3" rx="1.5" fill="var(--muted-foreground)" opacity=".14"/>
    <rect x="416" y="259" width="9"  height="3" rx="1.5" fill="var(--muted-foreground)" opacity=".11"/>
    <text x="416" y="292" fill="var(--muted-foreground)" font-size="13">thousands more</text>
  </g>
</svg>`
/** Figure 8 — A ranked list (M1 s3) */
export function Fig08() { return <Reveal svg={SVG_08} label={"The output is a whole ranked distribution, and even the winning token is a sliver of it."} /> }

const SVG_09 = `<svg viewBox="0 0 960 380" xmlns="http://www.w3.org/2000/svg" fill="none">
  <g id="f09-header"><text x="220" y="82" fill="var(--muted-foreground)" font-size="13" text-anchor="end">per step</text></g>
  <g id="f09-rail1">
    <path d="M240.0 110 H840.0" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M240 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M300 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M360 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M420 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M480 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M540 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M600 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M660 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M720 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M780 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M840 104 V116" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <rect x="240" y="102" width="543" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <text x="220" y="115" fill="var(--muted-foreground)" font-size="15" text-anchor="end">99%</text>
  </g>
  <g id="f09-rail2">
    <path d="M240.0 190 H840.0" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M240 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M300 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M360 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M420 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M480 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M540 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M600 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M660 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M720 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M780 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M840 184 V196" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <rect x="240" y="182" width="359" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <text x="220" y="195" fill="var(--muted-foreground)" font-size="15" text-anchor="end">95%</text>
  </g>
  <g id="f09-rail3">
    <path d="M240.0 270 H840.0" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M240 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M300 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M360 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M420 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M480 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M540 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M600 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M660 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M720 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M780 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <path d="M840 264 V276" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <rect x="240" y="262" width="209" height="16" rx="3" fill="var(--figure-accent)"/>
    <text x="220" y="275" fill="currentColor" font-size="15" text-anchor="end">90%</text>
    <text x="467" y="275" fill="currentColor" font-size="15">35% still right</text>
  </g>
  <g id="f09-axis"><text x="540" y="330" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">ten steps</text></g>
</svg>`
/** Figure 9 — Ninety percent, ten times (M5 s5) */
export function Fig09() { return <Reveal svg={SVG_09} label={"Per-step reliability multiplies: 90% a step leaves a third of the task standing by step ten."} /> }

const SVG_10 = `<svg viewBox="0 0 960 400" xmlns="http://www.w3.org/2000/svg" fill="none">
  <g id="f10-row1">
    <rect x="300" y="84" width="84" height="16" rx="3" fill="var(--muted-foreground)" opacity=".42"/>
    <text x="170" y="97" fill="currentColor" font-size="13">plan</text>
  </g>
  <g id="f10-row2">
    <rect x="392" y="118" width="332" height="16" rx="3" fill="var(--muted-foreground)" opacity=".28"/>
    <text x="170" y="131" fill="currentColor" font-size="13">research</text>
  </g>
  <g id="f10-row3">
    <rect x="400" y="152" width="166" height="16" rx="3" fill="var(--muted-foreground)" opacity=".42"/>
    <text x="192" y="165" fill="var(--muted-foreground)" font-size="13">search</text>
  </g>
  <g id="f10-row4">
    <rect x="400" y="186" width="212" height="16" rx="3" fill="var(--muted-foreground)" opacity=".42"/>
  </g>
  <g id="f10-row5">
    <rect x="400" y="220" width="318" height="16" rx="3" fill="var(--figure-accent)"/>
    <text x="734" y="233" fill="currentColor" font-size="13">slowest</text>
  </g>
  <g id="f10-row6">
    <rect x="732" y="254" width="62" height="16" rx="3" fill="var(--muted-foreground)" opacity=".42"/>
    <text x="170" y="267" fill="currentColor" font-size="13">check</text>
  </g>
  <g id="f10-row7">
    <rect x="802" y="288" width="76" height="16" rx="3" fill="var(--muted-foreground)" opacity=".42"/>
    <text x="170" y="301" fill="currentColor" font-size="13">write</text>
  </g>
  <g id="f10-axis">
    <path d="M300 322 H880" stroke="var(--muted-foreground)" stroke-width="1.5" opacity=".3"/>
    <text x="590" y="348" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">time</text>
  </g>
</svg>`
/** Figure 10 — One run, read back (M8 s6) */
export function Fig10() { return <Reveal svg={SVG_10} label={"Nesting shows who called whom, a shared time axis shows what ran at once, one bar shows where the time went."} /> }

const SVG_11 = `<svg viewBox="0 0 960 460" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f11-ink11" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f11-acc11" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f11-untrusted">
    <text x="480" y="86" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">untrusted text</text>
    <rect x="428" y="102" width="104" height="8" rx="4" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="443" y="118" width="74" height="8" rx="4" fill="var(--muted-foreground)" opacity=".5"/>
    <rect x="435" y="134" width="90" height="8" rx="4" fill="var(--muted-foreground)" opacity=".5"/>
  </g>

  <g id="f11-private">
    <rect x="112" y="262" width="116" height="55" fill="var(--fig-bg)"/>
    <path d="M112 262 V317" stroke="currentColor" stroke-width="2"/>
    <path d="M228 262 V317" stroke="currentColor" stroke-width="2"/>
    <path d="M112 317 A58 15 0 0 0 228 317" stroke="currentColor" stroke-width="2"/>
    <ellipse cx="170" cy="262" rx="58" ry="15" fill="var(--fig-bg)" stroke="currentColor" stroke-width="2"/>
    <text x="170" y="368" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">private data</text>
  </g>

  <g id="f11-model">
    <rect x="380" y="230" width="200" height="120" rx="16" stroke="currentColor" stroke-width="2"/>
    <text x="480" y="296" fill="currentColor" font-size="15" text-anchor="middle">model</text>
  </g>

  <g id="f11-tool">
    <rect x="760" y="258" width="64" height="64" rx="8" fill="var(--figure-accent)"/>
    <polyline points="801,266 785,290 798,290 783,314" fill="none" stroke="var(--fig-bg)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>
    <text x="792" y="356" fill="currentColor" font-size="13" text-anchor="middle">a way out</text>
  </g>

  <g id="f11-path">
    <path d="M480 142 V230" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f11-acc11)"/>
    <path d="M228 290 H380" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f11-acc11)"/>
    <path d="M580 290 H760" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f11-acc11)"/>
  </g>
</svg>`
/** Figure 11 — The lethal trifecta (M6 s4) */
export function Fig11() { return <Reveal svg={SVG_11} label={"No single capability is dangerous; the breach is one agent holding private data, untrusted text, and a way out at the same time."} /> }

const SVG_12 = `<svg viewBox="0 0 960 460" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f12-ink12" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f12-acc12" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f12-mut12" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f12-boundary">
    <rect x="145" y="92" width="370" height="282" rx="14" stroke="var(--muted-foreground)" opacity=".5" stroke-width="1.5" stroke-dasharray="5 5"/>
    <text x="167" y="120" fill="var(--muted-foreground)" font-size="13" text-anchor="start">everything you have</text>
  </g>

  <g id="f12-field" fill="var(--muted-foreground)" opacity=".38">
    <rect x="172" y="136" width="26" height="8" rx="4"/>
    <rect x="214" y="162" width="26" height="8" rx="4"/>
    <rect x="166" y="180" width="26" height="8" rx="4"/>
    <rect x="256" y="138" width="26" height="8" rx="4"/>
    <rect x="302" y="164" width="26" height="8" rx="4"/>
    <rect x="238" y="198" width="26" height="8" rx="4"/>
    <rect x="344" y="130" width="26" height="8" rx="4"/>
    <rect x="396" y="158" width="26" height="8" rx="4"/>
    <rect x="440" y="134" width="26" height="8" rx="4"/>
    <rect x="470" y="170" width="26" height="8" rx="4"/>
    <rect x="356" y="184" width="26" height="8" rx="4"/>
    <rect x="416" y="186" width="26" height="8" rx="4"/>
    <rect x="168" y="250" width="26" height="8" rx="4"/>
    <rect x="216" y="220" width="26" height="8" rx="4"/>
    <rect x="164" y="298" width="26" height="8" rx="4"/>
    <rect x="252" y="318" width="26" height="8" rx="4"/>
    <rect x="188" y="334" width="26" height="8" rx="4"/>
    <rect x="306" y="342" width="26" height="8" rx="4"/>
    <rect x="356" y="320" width="26" height="8" rx="4"/>
    <rect x="414" y="344" width="26" height="8" rx="4"/>
    <rect x="462" y="314" width="26" height="8" rx="4"/>
  </g>

  <g id="f12-question">
    <circle cx="302" cy="252" r="11" fill="var(--fig-bg)" stroke="currentColor" stroke-width="3"/>
    <text x="279" y="257" fill="currentColor" font-size="13" text-anchor="end">question</text>
  </g>

  <g id="f12-nearest" fill="var(--figure-accent)">
    <rect x="314" y="207" width="26" height="8" rx="4"/>
    <rect x="336" y="240" width="26" height="8" rx="4"/>
    <rect x="312" y="290" width="26" height="8" rx="4"/>
  </g>

  <g id="f12-carry">
    <path d="M348 211 L665 228" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f12-acc12)"/>
    <path d="M370 244 L665 254" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f12-acc12)"/>
    <path d="M346 294 L665 280" stroke="var(--figure-accent)" stroke-width="2.5" marker-end="url(#f12-acc12)"/>
  </g>

  <g id="f12-window">
    <rect x="665" y="118" width="150" height="230" rx="10" stroke="currentColor" stroke-width="2"/>
    <rect x="685" y="168" width="110" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="685" y="194" width="110" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <text x="740" y="100" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">window</text>
  </g>

  <g id="f12-landed" fill="var(--figure-accent)">
    <rect x="685" y="220" width="110" height="16" rx="3"/>
    <rect x="685" y="246" width="110" height="16" rx="3"/>
    <rect x="685" y="272" width="110" height="16" rx="3"/>
  </g>
</svg>`
/** Figure 12 — Nearest in meaning (M4 s4) */
export function Fig12() { return <Reveal svg={SVG_12} label={"Chunks sit in a space of meaning, and only the few nearest the question ever enter the window."} /> }

const SVG_13 = `<svg viewBox="0 0 960 420" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f13-ink13" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f13-mut13" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--muted-foreground)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f13-tray-a">
    <rect x="195" y="80" width="170" height="260" rx="10" stroke="currentColor" stroke-width="2"/>
  </g>

  <g id="f13-tray-a-contents">
    <rect x="215" y="102" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="127" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="152" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="177" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="202" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="227" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="252" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="277" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="215" y="302" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
  </g>

  <g id="f13-fold">
    <path d="M365 210 H595" stroke="var(--muted-foreground)" stroke-width="1.5" marker-end="url(#f13-mut13)"/>
    <text x="480" y="194" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">compact</text>
  </g>

  <g id="f13-tray-b">
    <rect x="595" y="80" width="170" height="260" rx="10" stroke="currentColor" stroke-width="2"/>
  </g>

  <g id="f13-summary">
    <rect x="615" y="102" width="130" height="44" rx="3" fill="var(--figure-accent)"/>
  </g>

  <g id="f13-tray-b-contents">
    <rect x="615" y="170" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="615" y="195" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="615" y="220" width="130" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
  </g>

  <g id="f13-room">
    <text x="615" y="292" fill="var(--muted-foreground)" font-size="13" text-anchor="start">room</text>
  </g>
</svg>`
/** Figure 13 — Folding the transcript (M4 s2) */
export function Fig13() { return <Reveal svg={SVG_13} label={"Compaction folds the old turns into one summary block, leaves the recent turns verbatim, and gives the window room again."} /> }

const SVG_14 = `<svg viewBox="0 0 960 440" xmlns="http://www.w3.org/2000/svg" fill="none">
  <defs>
    <marker id="f14-ink14" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
    <marker id="f14-acc14" viewBox="0 0 10 10" refX="8.6" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0.8 1 L8.4 5 L0.8 9" fill="none" stroke="var(--figure-accent)" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>

  <g id="f14-window">
    <rect x="150" y="96" width="170" height="240" rx="10" stroke="currentColor" stroke-width="2"/>
    <rect x="172" y="116" width="126" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="172" y="144" width="126" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
    <rect x="172" y="200" width="126" height="16" rx="3" fill="var(--muted-foreground)" opacity=".4"/>
  </g>

  <g id="f14-accent">
    <rect x="172" y="172" width="126" height="16" rx="3" fill="var(--figure-accent)"/>
  </g>

  <g id="f14-boundary">
    <rect x="505" y="170" width="310" height="166" rx="14" stroke="var(--muted-foreground)" opacity=".5" stroke-width="1.5" stroke-dasharray="5 5"/>
    <text x="527" y="198" fill="var(--muted-foreground)" font-size="13" text-anchor="start">your code</text>
  </g>

  <g id="f14-tool">
    <rect x="628" y="216" width="64" height="64" rx="8" fill="var(--fig-bg)" stroke="currentColor" stroke-width="2"/>
    <polyline points="669,224 653,248 666,248 651,272" fill="none" stroke="var(--muted-foreground)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>
    <text x="660" y="304" fill="var(--muted-foreground)" font-size="13" text-anchor="middle">tool</text>
  </g>

  <g id="f14-out">
    <path d="M320 152 H660 V215.5" stroke="currentColor" stroke-width="2" marker-end="url(#f14-ink14)"/>
  </g>

  <g id="f14-back">
    <path d="M628 248 H430 V180 H323" stroke="var(--figure-accent)" stroke-width="3" marker-end="url(#f14-acc14)"/>
    <text x="375" y="208" fill="currentColor" font-size="13" text-anchor="middle">result</text>
  </g>
</svg>`
/** Figure 14 — The round trip, in order (M3 s3) */
export function Fig14() { return <Reveal svg={SVG_14} label={"A tool result is just another message in the window — the model reads it, it does not know it."} /> }

export const figureCaptions: Record<string, string> = {
  "01": "FIGURE 4.1 — Pick, append, repeat.",
  "02": "FIGURE 2 — The model reads all of it, every call, and keeps none of it.",
  "03": "FIGURE 3 — The model asks. Your code is what actually runs.",
  "04": "FIGURE 4 — The loop, and the one way out of it.",
  "05": "FIGURE 4.3.1 — Memory that survives the window: a file.",
  "06": "FIGURE 6 — Three gates your code owns, around a loop it doesn't.",
  "07": "FIGURE 7 — The Desk. Every part is a loop you have already built.",
  "08": "FIGURE 3.1 — Not an answer. A list of possible next tokens, with odds.",
  "09": "FIGURE 5.5.1 — Small per-step errors, large end-to-end failure.",
  "10": "FIGURE 8.6.1 — One run, fully visible. This is the page people will stare at.",
  "11": "FIGURE 6.4.1 — Any two is a risk. All three is a breach waiting to happen.",
  "12": "FIGURE 4.4.1 — Don't load the library; load the three pages that matter.",
  "13": "FIGURE 4.2.1 — Compaction: trade detail for room.",
  "14": "FIGURE 3.3.1 — One tool use is two messages and a function call in between.",
}
